# Keep this file updated with the config/secrets.yml keys

development:
  secret_key_base: password

test:
  secret_key_base: password

staging:
  secret_key_base: password
  errbit_api_key: password
  errbit_host: password
  trello_url: password

production:
  secret_key_base: password
  errbit_api_key: password
  errbit_host: password
